name: prime_pin_code
description: This package provide out of the box entering PIN code functionality, which can be used
  for seting, editing and verifying a PIN code. It can be used with or Without Biometric Authentication.

version: 0.0.1
homepage: https://primeholding.com/

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=3.7.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_rx_bloc: ^5.0.2
  flutter_svg: ^2.0.0+1
  prime_biometrics:
  provider: ^6.0.5
  rx_bloc: ^4.0.0
  rx_bloc_list: ^3.2.1
  rxdart: ^0.27.7
  theme_tailor_annotation: ^1.0.3
  widget_toolkit:

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.14.0
  mockito: ^5.3.2
  rx_bloc_generator: ^6.0.1
  rx_bloc_test: ^3.3.3
  theme_tailor: ^1.0.8


dependency_overrides:
  widget_toolkit:
    path: ../widget_toolkit
  widget_toolkit_biometrics:
    path: ../widget_toolkit_biometrics


flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf

  assets:
    - packages/prime_pin_code/icons/faceScanDefault.svg
    - packages/prime_pin_code/icons/faceScanInverted.svg
    - packages/prime_pin_code/icons/faceScanPressed.svg
    - packages/prime_pin_code/icons/fingerScanDefault.svg
    - packages/prime_pin_code/icons/fingerScanInverted.svg
    - packages/prime_pin_code/icons/fingerScanPressed.svg
    - packages/prime_pin_code/icons/infoCircle.svg
    - packages/prime_pin_code/icons/pinCheckEnabled.svg
    - packages/prime_pin_code/icons/pinCheckDisabled.svg
    - packages/prime_pin_code/icons/pinDeleteAction.svg
    - packages/prime_pin_code/icons/pinDeleteDefault.svg
    - packages/prime_pin_code/icons/pinNextEnabled.svg
    - packages/prime_pin_code/icons/pinNextDisabled.svg