// Mocks generated by Mockito 5.4.6 from annotations
// in widget_toolkit_biometrics/test/src/service/biometrics_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:widget_toolkit_biometrics/src/data_sources/biometrics_auth_data_source.dart'
    as _i2;
import 'package:widget_toolkit_biometrics/src/data_sources/biometrics_local_data_source.dart'
    as _i3;
import 'package:widget_toolkit_biometrics/src/repositories/biometrics_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBiometricsAuthDataSource_0 extends _i1.SmartFake
    implements _i2.BiometricsAuthDataSource {
  _FakeBiometricsAuthDataSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBiometricsLocalDataSource_1 extends _i1.SmartFake
    implements _i3.BiometricsLocalDataSource {
  _FakeBiometricsLocalDataSource_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BiometricsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBiometricsRepository extends _i1.Mock
    implements _i4.BiometricsRepository {
  MockBiometricsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BiometricsAuthDataSource get biometricAuthenticationDataSource =>
      (super.noSuchMethod(
        Invocation.getter(#biometricAuthenticationDataSource),
        returnValue: _FakeBiometricsAuthDataSource_0(
          this,
          Invocation.getter(#biometricAuthenticationDataSource),
        ),
      ) as _i2.BiometricsAuthDataSource);

  @override
  _i3.BiometricsLocalDataSource get localDataSource => (super.noSuchMethod(
        Invocation.getter(#localDataSource),
        returnValue: _FakeBiometricsLocalDataSource_1(
          this,
          Invocation.getter(#localDataSource),
        ),
      ) as _i3.BiometricsLocalDataSource);

  @override
  _i5.Future<bool> get canCheckBiometrics => (super.noSuchMethod(
        Invocation.getter(#canCheckBiometrics),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> get isDeviceSupported => (super.noSuchMethod(
        Invocation.getter(#isDeviceSupported),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> authenticate(String? localizedReason) => (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [localizedReason],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setBiometricsEnabled(bool? areBiometricsEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBiometricsEnabled,
          [areBiometricsEnabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> areBiometricsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #areBiometricsEnabled,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}
