name: widget_toolkit
description: The Widget Toolkit package consists of several lightweight and customisable UI components that boost productivity and reduce the development time.
version: 0.0.1-dev1
repository: https://github.com/Prime-Holding/widget_toolkit
issue_tracker: https://github.com/Prime-Holding/widget_toolkit/issues
homepage: https://www.primeholding.com

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  copy_with_extension: ^5.0.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rx_bloc: ^5.0.0
  flutter_svg: ^2.0.0
  json_annotation: ^4.8.0
  provider: ^6.0.0
  rx_bloc: ^4.0.0
  rxdart: ^0.27.7
  shimmer: ^2.0.0
  theme_tailor_annotation: ^1.0.0
  url_launcher: ^6.1.0

dev_dependencies:
  build_runner: ^2.3.3
  clean_coverage: ^0.0.3
  copy_with_extension_gen: ^5.0.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  json_serializable: ^6.6.0
  mockito: ^5.3.2
  r_flutter: ^0.9.0
  rx_bloc_generator: ^6.0.1
  rx_bloc_test: ^3.3.3
  theme_tailor: ^1.0.8

flutter:
  uses-material-design: true

  assets:
    - packages/widget_toolkit/icons/info-circle.svg
    - packages/widget_toolkit/icons/arrow-right-square.svg
    - packages/widget_toolkit/icons/add.svg
    - packages/widget_toolkit/icons/check.svg
    - packages/widget_toolkit/icons/check_circle.svg
    - packages/widget_toolkit/icons/close.svg
    - packages/widget_toolkit/icons/danger.svg
    - packages/widget_toolkit/icons/edit-pen.svg
    - packages/widget_toolkit/icons/loading.svg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        
screenshots:
  - description: Item picker (multi-select)
    path: doc/assets/multi-item-picker.gif
  - description: Item picker (single-select)
    path: doc/assets/single-item-picker.gif
  - description: Language Picker
    path: doc/assets/language-picker.gif
  - description: Search Picker
    path: doc/assets/search-picker.gif
  - description: Shimmer Widget
    path: doc/assets/shimmeritem_picker_bloc.gif
  - description: URL Launcher
    path: doc/assets/url.gif
  - description: Error Buttom Sheet
    path: doc/assets/error-bottom-sheet.gif
  - description: Text Field Dialog
    path: doc/assets/text-field-dialog.gif
  - description: Address Dialog
    path: doc/assets/address.gif
