name: widget_toolkit
description: A collection of customisable widgets developed by PrimeHolding JSC to help reduce development time
version: 0.0.1-dev1
homepage: https://primeholding.com/

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=3.7.1"

dependencies:
  copy_with_extension: ^5.0.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rx_bloc: ^5.0.0
  flutter_svg: ^2.0.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.0
  provider: ^6.0.0
  rx_bloc: ^4.0.0
  rxdart: ^0.27.7
  shimmer: ^2.0.0
  theme_tailor_annotation: ^1.0.0
  url_launcher: ^6.1.0

dev_dependencies:
  build_runner: ^2.3.3
  clean_coverage: ^0.0.3
  copy_with_extension_gen: ^5.0.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  mockito: ^5.3.2
  r_flutter: ^0.9.0
  rx_bloc_generator: ^6.0.1
  rx_bloc_test: ^3.3.3
  theme_tailor: ^1.0.8

flutter:
  uses-material-design: true

  assets:
    - packages/widget_toolkit/icons/info-circle.svg
    - packages/widget_toolkit/icons/arrow-right-square.svg
    - packages/widget_toolkit/icons/add.svg
    - packages/widget_toolkit/icons/check.svg
    - packages/widget_toolkit/icons/check_circle.svg
    - packages/widget_toolkit/icons/close.svg
    - packages/widget_toolkit/icons/danger.svg
    - packages/widget_toolkit/icons/edit-pen.svg
    - packages/widget_toolkit/icons/loading.svg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        
 screenshots:
  - description: Item picker (multi-select)
    path: docs/multi-item-picker.gif
  - description: Item picker (single-select)
    path: docs/single-item-picker.gif
  - description: Language Picker
    path: docs/language-picker.gif
  - description: Search Picker
    path: docs/search-picker.gif
  - description: Shimmer
    path: docs/shimmer.gif
   - description: URL Launcher
    path: docs/url.gif
  - description: Error Button Sheet
    path: docs/error-bottom-sheet.gif
  - description: Text Field Dialog
    path: docs/text-field-dialog.gif
  - description: Address Dialog
    path: docs/address.gif
