name: qr_example
description: An example project to present how to use widget_toolkit_qr package with minimal effort.
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  widget_toolkit: ^0.0.1-dev6
  widget_toolkit_qr:

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
