name: qr_example
description: An example project to present how to use widget_toolkit_qr package with minimal effort.
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  widget_toolkit: ^0.0.2-dev.1
  widget_toolkit_qr: ^0.0.2-dev.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
