name: example
description: An example project to present how to use widget_toolkit_biometrics package with minimal effort.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  app_settings: ^5.0.0
  flutter:
    sdk: flutter
  flutter_rx_bloc: ^7.0.0
  provider: ^6.0.5
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  widget_toolkit: ^0.2.0
  widget_toolkit_biometrics: ^0.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
