name: example
description: An example project to present how to use widget_toolkit_biometrics package with minimal effort.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  app_settings: ^5.0.0
  flutter:
    sdk: flutter
  flutter_rx_bloc: ^6.0.0
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  widget_toolkit: ^0.0.2-dev.1
  widget_toolkit_biometrics: ^0.0.2-dev.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
