name: widget_toolkit_otp
description: Package helping with building sms or pin code fields and screens in a matter of minutes
version: 0.0.1-dev2
homepage: https://primeholding.com/

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=3.7.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rx_bloc: ^5.0.2
  pinput: ^2.2.23
  provider: ^6.0.5
  rx_bloc: ^4.0.0
  rxdart: ^0.27.7
  theme_tailor_annotation: ^1.0.3
  widget_toolkit: ^0.0.1-dev6

dev_dependencies:
  build_runner: ^2.3.3
  clean_coverage: ^0.0.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.14.0
  mockito: ^5.3.2
  rx_bloc_generator: ^6.0.1
  rx_bloc_test: ^3.3.3
  theme_tailor: ^1.0.8

flutter:
  uses-material-design: true

screenshots:
  - description: "SMS OTP Field"
    path: doc/assets/otp-example.webp