name: widget_toolkit_otp
description: Package helping with building sms or pin code fields and screens in a matter of minutes
version: 0.1.0
homepage: https://primeholding.com/

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rx_bloc: ^7.0.0
  pinput: ^5.0.0
  provider: ^6.0.5
  rx_bloc: ^6.0.0
  rxdart: ^0.28.0
  theme_tailor_annotation: ^3.0.0
  widget_toolkit: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.12
  clean_coverage: ^0.0.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  mockito: ^5.4.2
  rx_bloc_generator: ^8.0.0
  rx_bloc_test: ^5.0.0
  theme_tailor: ^3.0.0

flutter:
  uses-material-design: true

screenshots:
  - description: "SMS OTP Field"
    path: doc/assets/otp-example.webp
