name: example
description: An example project to present how to use widget_toolkit package with minimal effort.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rx_bloc: ^6.0.0
  rxdart:
  widget_toolkit: ^0.0.1-dev10

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  widget_toolkit:
    path: ../../widget_toolkit

flutter:
  uses-material-design: true
