name: widget_toolkit
description: The Widget Toolkit package consists of several lightweight and customisable UI components that boost productivity and reduce the development time.
version: 0.0.2
repository: https://github.com/Prime-Holding/widget_toolkit/tree/master/packages/widget_toolkit
issue_tracker: https://github.com/orgs/Prime-Holding/projects/6
homepage: https://www.primeholding.com

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  copy_with_extension: ^5.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rx_bloc: ^6.0.0
  flutter_svg: ^2.0.7
  json_annotation: ^4.8.1
  provider: ^6.0.5
  rx_bloc: ^5.0.0
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  theme_tailor_annotation: ^3.0.0
  url_launcher: ^6.1.12

dev_dependencies:
  build_runner: ^2.4.6
  clean_coverage: ^0.0.3
  copy_with_extension_gen: ^5.0.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  r_flutter: ^0.9.0
  rx_bloc_generator: ^7.0.0
  rx_bloc_test: ^4.0.0
  theme_tailor: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - packages/widget_toolkit/icons/add.svg
    - packages/widget_toolkit/icons/add-disabled.svg
    - packages/widget_toolkit/icons/arrow-left.svg
    - packages/widget_toolkit/icons/arrow-right-square.svg
    - packages/widget_toolkit/icons/camera.svg
    - packages/widget_toolkit/icons/check.svg
    - packages/widget_toolkit/icons/check_circle.svg
    - packages/widget_toolkit/icons/close.svg
    - packages/widget_toolkit/icons/close-qr-scanner.svg
    - packages/widget_toolkit/icons/danger.svg
    - packages/widget_toolkit/icons/edit-pen.svg
    - packages/widget_toolkit/icons/educate.svg
    - packages/widget_toolkit/icons/great_news.svg
    - packages/widget_toolkit/icons/info-circle.svg
    - packages/widget_toolkit/icons/loading.svg
    - packages/widget_toolkit/icons/message.svg
    - packages/widget_toolkit/icons/qr-scan-area.svg
    - packages/widget_toolkit/icons/tick-circle-success.svg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf

screenshots:
  - description: "Item picker (multi-select)"
    path: doc/assets/multi-item-picker.webp
  - description: "Item picker (single-select)"
    path: doc/assets/single-item-picker.webp
  - description: "Language Picker"
    path: doc/assets/language-picker.webp
  - description: "Search Picker"
    path: doc/assets/search-picker.webp
  - description: "Shimmer Widget"
    path: doc/assets/shimmer.webp
  - description: "URL Launcher"
    path: doc/assets/url.webp
  - description: "Error Bottom Sheet"
    path: doc/assets/error-bottom-sheet.webp
  - description: "Text Field Dialog"
    path: doc/assets/text-field-dialog.webp
  - description: "Address Dialog"
    path: doc/assets/address.webp
