// Mocks generated by Mockito 5.4.4 from annotations
// in widget_toolkit_qr/test/lib_qr_scanner/services/system_permissions_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:permission_handler/permission_handler.dart' as _i4;
import 'package:widget_toolkit_qr/src/lib_qr_scanner/repositories/system_permissions_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SystemPermissionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSystemPermissionsRepository extends _i1.Mock
    implements _i2.SystemPermissionsRepository {
  MockSystemPermissionsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> checkForCameraPermissions() => (super.noSuchMethod(
        Invocation.method(
          #checkForCameraPermissions,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i4.PermissionStatus> requestCameraPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestCameraPermission,
          [],
        ),
        returnValue:
            _i3.Future<_i4.PermissionStatus>.value(_i4.PermissionStatus.denied),
      ) as _i3.Future<_i4.PermissionStatus>);

  @override
  _i3.Future<void> openPhoneAppSettings() => (super.noSuchMethod(
        Invocation.method(
          #openPhoneAppSettings,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
