name: widget_toolkit_biometrics
description: A Flutter package that helps users to handle enabling and disabling biometrics in an application
version: 0.0.3
repository: https://github.com/Prime-Holding/widget_toolkit/tree/master/packages/widget_toolkit_biometrics
issue_tracker: https://github.com/orgs/Prime-Holding/projects/6
homepage: https://primeholding.com/

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5"

dependencies:
  app_settings: ^5.1.1
  flutter:
    sdk: flutter
  flutter_rx_bloc: ^7.0.0
  local_auth: ^2.3.0
  provider: ^6.1.2
  rx_bloc: ^6.0.0
  rxdart: ^0.28.0
  widget_toolkit: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.12
  clean_coverage: ^0.0.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  rx_bloc_generator: ^8.0.0
  rx_bloc_test: ^5.0.0

flutter:
  uses-material-design: true

screenshots:
  - description: "Success Scenario"
    path: doc/assets/success.webp
  - description: "Not Supported Scenario"
    path: doc/assets/not_supported.webp
  - description: "Not Setup Scenario"
    path: doc/assets/not_setup.webp
