name: widget_toolkit_biometrics
description: A Flutter package that helps users to handle enabling and disabling biometrics in an application
version: 0.0.1-dev1
repository: https://github.com/Prime-Holding/widget_toolkit/packages/widget_toolkit_biometrics
issue_tracker: https://github.com/orgs/Prime-Holding/projects/6
homepage: https://primeholding.com/

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=3.7.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_rx_bloc: ^5.0.2
  local_auth: ^2.1.3
  provider: ^6.0.5
  rx_bloc: ^4.0.0
  rxdart: ^0.27.7
  shared_preferences: ^2.0.17
  widget_toolkit:

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  rx_bloc_generator: ^6.0.1
  rx_bloc_test: ^3.3.3

flutter:
  uses-material-design: true

dependency_overrides:
  widget_toolkit:
    path: ../widget_toolkit
