name: widget_toolkit_pin
description: This package provide out of the box entering PIN code
  functionality, which can be used with biometric authentication.
version: 0.1.0
homepage: https://primeholding.com/

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5"

dependencies:
  app_settings: ^5.1.1
  flutter:
    sdk: flutter
  flutter_rx_bloc: ^6.0.0
  flutter_svg: ^2.0.7
  local_auth: ^2.1.7
  provider: ^6.0.5
  rx_bloc: ^5.0.0
  rx_bloc_list: ^4.0.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  theme_tailor_annotation: ^3.0.0
  widget_toolkit: ^0.0.2
  widget_toolkit_biometrics: ^0.0.2

dev_dependencies:
  build_runner: ^2.4.6
  clean_coverage: ^0.0.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  mockito: ^5.4.2
  rx_bloc_generator: ^7.0.0
  rx_bloc_test: ^4.0.0
  theme_tailor: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf

  assets:
    - packages/widget_toolkit_pin/icons/faceScanDefault.svg
    - packages/widget_toolkit_pin/icons/faceScanInverted.svg
    - packages/widget_toolkit_pin/icons/faceScanPressed.svg
    - packages/widget_toolkit_pin/icons/fingerScanDefault.svg
    - packages/widget_toolkit_pin/icons/fingerScanInverted.svg
    - packages/widget_toolkit_pin/icons/fingerScanPressed.svg
    - packages/widget_toolkit_pin/icons/pinDeleteAction.svg
    - packages/widget_toolkit_pin/icons/pinDeleteDefault.svg

screenshots:
  - description: "Biometrics Authentication Scenario"
    path: doc/assets/biometrics_authentication.webp
  - description: "Biometrics Authentication On App Restart Scenario"
    path: doc/assets/biometrics_authentication_on_app_restart.webp
  - description: "Biometrics Not Setup Scenario"
    path: doc/assets/biometrics_not_setup.webp
  - description: "Biometrics Not Supported Scenario"
    path: doc/assets/biometrics_not_supported.webp
  - description: "Face Not Recognized Scenario"
    path: doc/assets/face_not_recognized.webp
  - description: "Initial Pin Save Scenario"
    path: doc/assets/initial_pin_save.webp
  - description: "Pin Biometrics Diagram"
    path: doc/assets/pin_biometrics_diagram.png
  - description: "Wrong Pin Code Scenario"
    path: doc/assets/wrong_pin_code.webp
