name: widget_toolkit_pin
description: This package provide out of the box entering PIN code functionality, which can be used
  for setting, editing and verifying a PIN code. It can be used with or Without Biometric Authentication.

version: 0.0.1-dev1
homepage: https://primeholding.com/

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=3.7.1"

dependencies:
  app_settings: ^4.2.0
  flutter:
    sdk: flutter
  flutter_rx_bloc: ^5.0.2
  flutter_svg: ^2.0.0+1
  local_auth: ^2.1.3
  provider: ^6.0.5
  rx_bloc: ^4.0.0
  rx_bloc_list: ^3.2.1
  rxdart: ^0.27.7
  shared_preferences: ^2.1.0
  theme_tailor_annotation: ^1.0.3
  widget_toolkit:
  widget_toolkit_biometrics:

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.14.0
  mockito: ^5.3.2
  rx_bloc_generator: ^6.0.2
  rx_bloc_test: ^3.3.3
  theme_tailor: ^1.2.0


dependency_overrides:
  widget_toolkit:
    path: ../widget_toolkit
  widget_toolkit_biometrics:
    path: ../widget_toolkit_biometrics


flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf

  assets:
    - packages/widget_toolkit_pin/icons/faceScanDefault.svg
    - packages/widget_toolkit_pin/icons/faceScanInverted.svg
    - packages/widget_toolkit_pin/icons/faceScanPressed.svg
    - packages/widget_toolkit_pin/icons/fingerScanDefault.svg
    - packages/widget_toolkit_pin/icons/fingerScanInverted.svg
    - packages/widget_toolkit_pin/icons/fingerScanPressed.svg
    - packages/widget_toolkit_pin/icons/infoCircle.svg
    - packages/widget_toolkit_pin/icons/pinDeleteAction.svg
    - packages/widget_toolkit_pin/icons/pinDeleteDefault.svg
