name: widget_toolkit_qr
description: A Flutter package which provides a QR scanner widget easy integratable into the application.
version: 0.0.2-dev.3
repository: https://github.com/Prime-Holding/widget_toolkit/tree/master/packages/widget_toolkit_qr
issue_tracker: https://github.com/orgs/Prime-Holding/projects/6
homepage: https://primeholding.com/

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5"

dependencies:
  app_settings: ^5.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_qr_bar_scanner: ^3.0.2
  flutter_rx_bloc: ^6.0.0
  flutter_svg: ^2.0.7
  permission_handler: ^11.0.0
  provider: ^6.0.5
  rx_bloc: ^5.0.0
  rxdart: ^0.27.7
  theme_tailor_annotation: ^2.0.0
  widget_toolkit: ^0.0.2-dev.2

dev_dependencies:
  build_runner: ^2.4.6
  clean_coverage: ^0.0.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  mockito: ^5.4.2
  rx_bloc_generator: ^7.0.0
  rx_bloc_test: ^4.0.0
  theme_tailor: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - packages/widget_toolkit_qr/icons/qr-scan-area.svg
    
    
screenshots:
  - description: "QR Widget (Permission Asked)"
    path: doc/assets/permission_asked.webp
  - description: "QR Widget (Error State)"
    path: doc/assets/scan_error.webp
  - description: "QR Widget (Success Asked)"
    path: doc/assets/scan_success.webp
