name: widget_toolkit_qr
description: A Flutter package which provides a QR scanner widget easy integratable into the application.
version: 0.0.1-dev2
repository: https://github.com/Prime-Holding/widget_toolkit/tree/master/packages/widget_toolkit_qr
issue_tracker: https://github.com/orgs/Prime-Holding/projects/6
homepage: https://primeholding.com/

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.7.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_qr_bar_scanner: ^3.0.2
  flutter_rx_bloc: ^5.0.2
  flutter_svg: ^2.0.0+1
  permission_handler: ^10.2.0
  provider: ^6.0.5
  rx_bloc: ^4.0.0
  rxdart: ^0.27.7
  theme_tailor_annotation: ^1.0.3
  widget_toolkit: ^0.0.1-dev7

dev_dependencies:
  build_runner: ^2.3.3
  clean_coverage: ^0.0.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.14.0
  mockito: ^5.3.2
  rx_bloc_generator: ^6.0.1
  rx_bloc_test: ^3.3.3
  theme_tailor: ^1.0.8

flutter:
  uses-material-design: true

  assets:
    - packages/widget_toolkit_qr/icons/qr-scan-area.svg
    
    
screenshots:
  - description: "QR Widget (Permission Asked)"
    path: doc/assets/permission_asked.webp
  - description: "QR Widget (Error State)"
    path: doc/assets/scan_error.webp
  - description: "QR Widget (Success Asked)"
    path: doc/assets/scan_success.webp
