name: CI

on:
  push:
    paths:
      - ".github/workflows/ci.yaml"
      - "packages/widget_toolkit/lib/**"
      - "packages/widget_toolkit/test/**"

  pull_request:
    paths:
      - ".github/workflows/ci.yaml"
      - "packages/widget_toolkit/lib/**"
      - "packages/widget_toolkit/test/**"

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: "stable"
      - run: dart --version
      - run: flutter --version 
      - name: Install Dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze lib
      - name: Run tests
        run: |
          if [ -d "test" ]; then
            flutter test --coverage --exclude-tags=not-tests
          fi
      - name: Remove unnecessary files
        run: flutter pub run clean_coverage clean --exclusions '**/.g.dart','**repository.dart','**rxb.g.dart','**_dependencies.dart' coverage/lcov.info
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: "coverage/lcov.info"
          min_coverage: 58
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs: [run_tests]
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo 'noop'
