name: 'Publish widget_toolkit to pub.dev'

on:
  push:
    tags:
      - 'widget_toolkit-v[0-9]+.[0-9]+.[0-9]+*'

# Publish using custom workflow
jobs:
  publish:
    name: 'Publish widget_toolkit to pub.dev'
    environment: pub.dev
    permissions:
      id-token: write # This is required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        working-directory: packages/widget_toolkit
        run: dart pub get
      - name: Dart format
        working-directory: packages/widget_toolkit
        run: dart format .
      - name: Publish
        working-directory: packages/widget_toolkit
        run: dart pub publish --force
