name: 'Publish widget_toolkit_biometrics to pub.dev'

on:
  push:
    branches:
      - master
    tags:
      - 'widget_toolkit_biometrics-v[0-9]+.[0-9]+.[0-9]+*'

# Publish using custom workflow
jobs:
  publish:
    name: 'Publish widget_toolkit_biometrics to pub.dev'
    environment: pub.dev
    permissions:
      id-token: write # This is required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: "stable"
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        working-directory: packages/widget_toolkit_biometrics
        run: dart pub get
      # Here you can insert custom steps you need
      # - run: dart tool/generate-code.dart
      - name: Publish
        working-directory: packages/widget_toolkit_biometrics
        run: dart pub publish --dry-run